name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync
    
    - name: Copy files to EC2 (excluding .git)
      run: |
        rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app
        
    - name: Deploy app
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd app
          sudo docker build -t react-app .
          sudo docker stop react-app || true
          sudo docker rm react-app || true
          sudo docker run -d -p 8000:3000 --name react-app react-app
        EOF

